@startuml

box "メモリ管理"
    participant "メイン"               as main
    participant "ページング\n管理"     as page
    participant "物理メモリ\n領域管理" as phys
    participant "メモリマップ\n管理"   as map
end box
participant "MLIB" as mlib
participant "CPU"  as cpu

activate main

main -> page: 初期化
activate page

page -> page: 操作領域マッピング情報初期化
page -> page: アイドルプロセス用\nページディレクトリ初期化
page -> page: アイドルプロセス用\nページテーブル初期化

'page -> page: ページディレクトリ切替
'activate page
'ref over page: ページディレクトリ切替
'page /[#DDDDDD]-- page:
'deactivate page

page -\ cpu: ページディレクトリ設定
page -\ cpu: ページング有効化
page -\ cpu: グローバルページ有効化

page -> mlib: ページディレクトリ管理テーブル初期化
activate mlib
ref over mlib: 動的配列
page <-- mlib:
deactivate mlib

page -> mlib: アイドルプロセス用管理情報取得
activate mlib
ref over mlib: 動的配列
page <-- mlib:
deactivate mlib

page -> page: アイドルプロセス用\n管理情報設定

main <-- page:
deactivate page

@enduml
