@startuml

box "メモリ管理"
    participant "ページング管理"     as page
    participant "物理メモリ領域管理" as phys
    participant "メモリ領域管理"     as area
end box

activate page

page -> phys: 物理メモリ領域割当( サイズ )
activate phys

break サイズ == 0
    page <-- phys: NULL
end break

phys -> phys: サイズ4KBアライメント

phys -> area: メモリ領域割当
activate area

ref over area: メモリ領域管理

phys <-- area: アドレス
deactivate area

page <-- phys: アドレス
deactivate phys

@enduml
